name: Build LCFG on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1 

      - name: Compile lcfg.exe
        run: call build.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lcfg.exe
          path: lcfg.exe
